ALTER TABLE tasks
    ADD COLUMN IF NOT EXISTS points INT NOT NULL DEFAULT 10 AFTER task_order,
    ADD COLUMN IF NOT EXISTS content TEXT NOT NULL AFTER points,
    ADD COLUMN IF NOT EXISTS solution TEXT NOT NULL AFTER content,
    ADD COLUMN IF NOT EXISTS is_completed BOOLEAN NOT NULL DEFAULT FALSE AFTER solution;
