name: Vue Lint

on:
  push:
    branches: [main]
    paths:
      - 'frontend-svc/**'

  pull_request:
    branches: [main]
    paths:
      - 'frontend-svc/**'

jobs:
  lint:
    name: Vue Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: frontend-svc
        run: npm install

      - name: Lint Vue code
        working-directory: frontend-svc
        run: npm run lint
